#ifndef ZCOMMON_STATUS_H
#define ZCOMMON_STATUS_H


#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>

typedef enum {
    RES_STATUS_CONTINUE = 100,
    RES_STATUS_SWITCHING_PROTOCOLS = 101,
    RES_STATUS_PROCESSING = 102,
    RES_STATUS_EARLY_HINTS = 103,
    RES_STATUS_OK = 200,
    RES_STATUS_CREATED = 201,
    RES_STATUS_ACCEPTED = 202,
    RES_STATUS_NON_AUTORITATIVE_INFORMATION = 203,
    RES_STATUS_NO_CONTENT = 204,
    RES_STATUS_RESET_CONTENT = 205,
    RES_STATUS_PARTIAL_CONETNT = 206,
    RES_STATUS_MULTI_STATUS = 207,
    RES_STATUS_ALREADY_REPORTED = 208,
    RES_STATUS_TRANSFORMATION_APPLIED = 214,
    RES_STATUS_IM_USED = 226,
    RES_STATUS_MULTIPLE_CHOICES = 300,
    RES_STATUS_MOVED_PERMANENTLY = 301,
    RES_STATUS_FOUND = 302,
    RES_STATUS_SEE_OTHER = 303,
    RES_STATUS_NOT_MODIFIED = 304,
    RES_STATUS_USE_PROXY = 305,
    RES_STATUS_TEMPORARY_REDIRECT = 307,
    RES_STATUS_PERMANENT_REDIRECT = 308,
    RES_STATUS_BAD_REQUEST = 400,
    RES_STATUS_UNAUTHORIZED = 401,
    RES_STATUS_PAYMENT_REQUIRED = 402,
    RES_STATUS_FORBIDDEN = 403,
    RES_STATUS_NOT_FOUND = 404,
    RES_STATUS_METHOD_NOT_ALLOWED = 405,
    RES_STATUS_NOT_ACCEPTABLE = 406,
    RES_STATUS_PROXY_AUTHENTICATION_REQUIRED = 407,
    RES_STATUS_REQUEST_TIMEOUT = 408,
    RES_STATUS_CONFLICT = 409,
    RES_STATUS_GONE = 410,
    RES_STATUS_LENGTH_REQUIRED = 411,
    RES_STATUS_PRECONDITION_FAILED = 412,
    RES_STATUS_PAYLOAD_TOO_LARGE = 413,
    RES_STATUS_REQUEST_URI_TOO_LONG = 414,
    RES_STATUS_UNSOPPORTED_MEDIA_TYPE = 415,
    RES_STATUS_REQUEST_RANGE_NOT_SATISFIABLE = 416,
    RES_STATUS_EXPECTATION_FAILED = 417,
    RES_STATUS_IM_A_TEAPOT = 418,
    RES_STATUS_PAGE_EXPIRED = 419,
    RES_STATUS_ENHANCE_YOUR_CALM = 420,
    RES_STATUS_MISDIRECTED_REQUEST = 421,
    RES_STATUS_UNPROCESSABLE_ENTITY = 422,
    RES_STATUS_LOCKED = 423,
    RES_STATUS_FAILED_DEPENDENCY = 424,
    RES_STATUS_TOO_EARLY = 425,
    RES_STATUS_UPGRADE_REQUIRED = 426,
    RES_STATUS_PRECONDITION_REQUIRED = 428,
    RES_STATUS_TOO_MANY_REQUESTS = 429,
    RES_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
    RES_STATUS_NO_RESPONSE = 444,
    RES_STATUS_BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS = 450,
    RES_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS = 451,
    RES_STATUS_SSL_CERTIFICATE_ERROR = 495,
    RES_STATUS_SSL_CERTIFICATE_REQUIRED = 496,
    RES_STATUS_TOKEN_EXPIRED_INVALID = 498,
    RES_STATUS_CLIENT_CLOSED_REQUEST = 499,
    RES_STATUS_INTERNAL_SERVER_ERROR = 500,
    RES_STATUS_NOT_IMPLEMENTED = 501,
    RES_STATUS_BAD_GATEWAY = 502,
    RES_STATUS_SERVICE_UNAVAILABLE = 503,
    RES_STATUS_GATEWAY_TIMEOUT = 504,
    RES_STATUS_VARIANT_ALSO_NEGOTIATES = 506,
    RES_STATUS_INSUFFICIENT_STORAGE = 507,
    RES_STATUS_LOOP_DETECTED = 508,
    RES_STATUS_BANDWITH_LIMIT_EXCEEDED = 509,
    RES_STATUS_NOT_EXTENDED = 510,
    RES_STATUS_NETWORK_AUTHENTICATION_REQUIRED = 511,
    RES_STATUS_WEB_SERVER_IS_DOWN = 521,
    RES_STATUS_CONNECTION_TIMED_OUT = 522,
    RES_STATUS_ORIGIN_IS_UNREACHABLE = 523,
    RES_STATUS_SSL_HANDSHAKE_FAILED = 525,
    RES_STATUS_SITE_FROZEN = 530,
    RES_STATUS_NETWORK_CONNECT_TIMEOUT_ERROR = 599
} status_code_e;

#ifdef __cplusplus
}
#endif

#endif
